### PR TITLE
link: handle custom-id and headling links

### PR DESCRIPTION
**Pull request by pkulev**
Hello! Thank you for such useful plugin!
I've added some functionality I need to generate confluence pages from my org files.

1. I use https://github.com/snosov1/toc-org plugin to automatically generate ToC tree on save hook, so there was need to convert heading links to atlassian anchors.
image

2. My friend used [[*Heading]] links in his articles, so I've implemented such thing too.

Tests included, all green =)

Signed-off-by: Pavel Kulyov <kulyov.pavel@gmail.com>

### CODE REVIEW

**Comment by pkulev** [comment]
@stig, checks are hanging :(

**Comment by stig** [comment]
@pkulev thank you for this contribution! Can you try to push again? I've enabled "build forks" in CircleCI.

**Comment by pkulev** [comment]
Yep, it worked!

**Review by stig — APPROVED** [review]
LGTM! Thank you for your contribution!

**Pull request merged**
